# Generated by Django 4.2 on 2025-03-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Марка телефона')),
                ('camera', models.DateField(max_length=55, verbose_name='Камера телефона')),
                ('memery', models.CharField(max_length=55, verbose_name='Память телефона')),
                ('year_realised', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
    ]
